### ISSUE TITLE
Changing a column type on my Users Table

### ISSUE THREAD

**Issue by bfellerath** [davidwoodsandersen/PizzaQuest#3]
Originally I generated a migration that added a column to my users table that had a column for "points_total" and I made the type a string. I want to go back and change the type to integer.

I tried this:

http://stackoverflow.com/questions/10343383/rails-migrations-tried-to-change-the-type-of-column-from-string-to-integer

I also tried to delete the migration but this is a migration that I already migrated. I need to make the type change in the schema.

The errors I have gotten when I tried to migrate are:

```
== 20150915190605 AddPointsTotalToUsers: migrating ============================
-- add_column(:users, :points_total, :integer)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "points_total" of relation "users" already exists
: ALTER TABLE "users" ADD "points_total" integer/Users/bryanfellerath/src/PizzaQuest/db/migrate/20150915190605_add_points_total_to_users.rb:3:in `change'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "points_total" of relation "users" already exists
: ALTER TABLE "users" ADD "points_total" integer
/Users/bryanfellerath/src/PizzaQuest/db/migrate/20150915190605_add_points_total_to_users.rb:3:in `change'
-e:1:in `<main>'
PG::DuplicateColumn: ERROR:  column "points_total" of relation "users" already exists
/Users/bryanfellerath/src/PizzaQuest/db/migrate/20150915190605_add_points_total_to_users.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Bryans-MacBook-Pro:PizzaQuest bryanfellerath$ ALTER TABLE "users" ADD "points_total" integer
-bash: ALTER: command not found
Bryans-MacBook-Pro:PizzaQuest bryanfellerath$ bin/rails g migration change_column_type
      invoke  active_record
      create    db/migrate/20150915191559_change_column_type.rb

```

and

```
== 20150915190605 AddPointsTotalToUsers: migrating ============================
-- add_column(:users, :points_total, :integer)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "points_total" of relation "users" already exists
: ALTER TABLE "users" ADD "points_total" integer/Users/bryanfellerath/src/PizzaQuest/db/migrate/20150915190605_add_points_total_to_users.rb:3:in `change'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "points_total" of relation "users" already exists
: ALTER TABLE "users" ADD "points_total" integer
/Users/bryanfellerath/src/PizzaQuest/db/migrate/20150915190605_add_points_total_to_users.rb:3:in `change'
-e:1:in `<main>'
PG::DuplicateColumn: ERROR:  column "points_total" of relation "users" already exists
/Users/bryanfellerath/src/PizzaQuest/db/migrate/20150915190605_add_points_total_to_users.rb:3:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

**Comment by emilylordahl** [comment]
Resolved!
