### ISSUE TITLE
Handling an ajax post

### ISSUE THREAD

**Issue by niddy1** [davidwoodsandersen/PizzaQuest#4]
I'm having trouble catching my ajax post, here is what I have in my controller:

```
 def create
      user = User.find_by({token: env['HTTP_TOKEN']})

     visit = user.visits.create(params)
     render json: visit
 end

 private

 # def visit_params
 #     params.require(:visit).permit(:review)
 # end

 def params
   params.require(:visit).permit(:review)
 end
```

This is whats showing up in my terminal when I click the button to post the request:

```
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
  app/controllers/api/visits_controller.rb:57:in `params'
```

**Comment by emilylordahl** [comment]
`params` is a keyword that refers to the `params` object. Because you are defining your whitelist method as `params`, your app might be confused. If you change it to `visit_params` does it throw the same error?

**Comment by niddy1** [comment]
if it run it with visit_params i get this:

```
ActionController::ParameterMissing (param is missing or the value is empty: visit):
  app/controllers/api/visits_controller.rb:54:in `visit_params'
  app/controllers/api/visits_controller.rb:19:in `create'

```

when i put byebug in the def create, i see this when i search for params:

```
(byebug) params
{"review"=>"asd", "controller"=>"api/visits", "action"=>"create"}

```

**Comment by emilylordahl** [comment]
@rapala61 is a miracle worker!
